version: "3.9"

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '${HTTP_PORT}80:80'
      - '${HTTPS_PORT}:443'
      - '${MANAGER_PORT}:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
