version: "3.9"

services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    
    container_name: proxy

    restart: always
    
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
      - '${MANAGEMENT_PORT}:81'

    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  default:
    name: ${NETWORK_NAME}
    external: true